/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	"/v1/categories": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List active categories */
		get: operations["listPublicCategories"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/v1/categories/{id_or_slug}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get active category by UUID or slug */
		get: operations["getPublicCategory"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/v1/products": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List active products */
		get: operations["listPublicProducts"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/v1/products/{id_or_slug}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get active product by UUID or slug */
		get: operations["getPublicProduct"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/v1/checkout": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Create order from cart items */
		post: operations["createCheckoutOrder"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/v1/ping": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Health / resource sample (client auth) */
		get: operations["getClientPing"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/internal/client-upsert": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Upsert API clients */
		post: operations["upsertInternalClients"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/internal/client-find": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Find clients by filter */
		post: operations["findInternalClients"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/internal/client-delete": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		/** Delete clients by filter */
		delete: operations["deleteInternalClients"];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/internal/categories": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List categories (admin) */
		get: operations["listAdminCategories"];
		put?: never;
		/** Create category */
		post: operations["createAdminCategory"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/internal/categories/{id_or_slug}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get category by UUID or slug (admin) */
		get: operations["getAdminCategory"];
		put?: never;
		post?: never;
		/** Delete category */
		delete: operations["deleteAdminCategory"];
		options?: never;
		head?: never;
		/** Update category */
		patch: operations["updateAdminCategory"];
		trace?: never;
	};
	"/internal/products": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List products (admin) */
		get: operations["listAdminProducts"];
		put?: never;
		/** Create product (multipart) */
		post: operations["createAdminProduct"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/internal/products/{id_or_slug}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get product by UUID or slug (admin) */
		get: operations["getAdminProduct"];
		put?: never;
		post?: never;
		/** Delete product */
		delete: operations["deleteAdminProduct"];
		options?: never;
		head?: never;
		/** Update product (multipart) */
		patch: operations["updateAdminProduct"];
		trace?: never;
	};
	"/internal/orders": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List orders */
		get: operations["listAdminOrders"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/internal/orders/{id_or_order_number}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Order detail with items */
		get: operations["getAdminOrder"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		ResponseEnvelope: {
			success: boolean;
			error: components["schemas"]["APIError"] | null;
			/** @description Response payload; shape depends on operation. */
			data: {
				[key: string]: unknown;
			} | null;
		};
		APIError: {
			/** @example NOT_FOUND */
			code?: string;
			message?: string;
			/** @description Optional structured details (e.g. insufficient stock per line). */
			details?: unknown;
		};
		PageMeta: {
			page?: number;
			limit?: number;
			total?: number;
			total_pages?: number;
		};
		Category: {
			/** Format: uuid */
			id?: string;
			name?: string;
			slug?: string;
			description?: string | null;
			is_active?: boolean;
			/** Format: date-time */
			created_at?: string;
			/** Format: date-time */
			updated_at?: string;
		};
		CategoryCreateInput: {
			name: string;
			slug?: string;
			description?: string | null;
			is_active?: boolean;
		};
		CategoryUpdateInput: {
			name?: string;
			slug?: string;
			description?: string | null;
			is_active?: boolean;
		};
		CategoryListData: {
			items?: components["schemas"]["Category"][];
			meta?: components["schemas"]["PageMeta"];
		};
		Product: {
			/** Format: uuid */
			id?: string;
			name?: string;
			slug?: string;
			description?: string;
			/**
			 * Format: int64
			 * @description Whole rupiah (IDR), integer amount
			 */
			price?: number;
			image_url?: string | null;
			/** Format: uuid */
			category_id?: string;
			stock?: number;
			is_active?: boolean;
			/** Format: date-time */
			created_at?: string;
			/** Format: date-time */
			updated_at?: string;
			category_name?: string;
			category_slug?: string;
		};
		ProductListData: {
			items?: components["schemas"]["Product"][];
			meta?: components["schemas"]["PageMeta"];
		};
		ProductCreateMultipartFields: {
			name: string;
			slug?: string;
			description?: string;
			/** @description Whole rupiah (IDR) as decimal integer string */
			price: string;
			/** Format: uuid */
			category_id: string;
			/** @description Non-negative integer as string */
			stock: string;
			/** @enum {string} */
			is_active?: "true" | "false";
			/**
			 * Format: binary
			 * @description JPEG, PNG, or WebP; max 5 MB
			 */
			image?: string;
		};
		ProductUpdateMultipartFields: {
			name?: string;
			slug?: string;
			description?: string;
			/** @description Whole rupiah (IDR) as decimal integer string */
			price?: string;
			/** Format: uuid */
			category_id?: string;
			stock?: string;
			/** @enum {string} */
			is_active?: "true" | "false";
			/** @enum {string} */
			remove_image?: "true";
			/**
			 * Format: binary
			 * @description JPEG, PNG, or WebP; max 5 MB
			 */
			image?: string;
		};
		Order: {
			/** Format: uuid */
			id?: string;
			order_number?: string;
			status?: string;
			customer_name?: string;
			customer_email?: string;
			customer_phone?: string | null;
			shipping_address?: string | null;
			/** Format: int64 */
			total?: number;
			/** Format: date-time */
			created_at?: string;
			/** Format: date-time */
			updated_at?: string;
			items?: components["schemas"]["OrderItem"][];
		};
		OrderItem: {
			/** Format: uuid */
			id?: string;
			/** Format: uuid */
			order_id?: string;
			/** Format: uuid */
			product_id?: string;
			product_name?: string;
			/** Format: int64 */
			unit_price?: number;
			quantity?: number;
			/** Format: int64 */
			line_total?: number;
			/** Format: date-time */
			created_at?: string;
		};
		OrderListData: {
			items?: components["schemas"]["Order"][];
			meta?: components["schemas"]["PageMeta"];
		};
		CheckoutRequest: {
			customer_name: string;
			customer_email: string;
			customer_phone?: string;
			shipping_address?: string;
			items: {
				/** Format: uuid */
				product_id: string;
				quantity: number;
			}[];
		};
		CheckoutResponse: {
			/** Format: uuid */
			id?: string;
			order_number?: string;
			status?: string;
			customer_name?: string;
			customer_email?: string;
			customer_phone?: string;
			shipping_address?: string;
			items?: {
				product_id?: string;
				product_name?: string;
				unit_price?: number;
				quantity?: number;
				line_total?: number;
			}[];
			/** Format: int64 */
			total?: number;
			created_at?: string;
		};
		ClientInput: {
			name?: string;
			bearer_key?: string;
			/** Format: date-time */
			created_at?: string;
			/** Format: date-time */
			updated_at?: string;
		};
		Client: {
			id?: number;
		} & components["schemas"]["ClientInput"];
		ClientFilter: {
			ids?: number[];
			names?: string[];
			bearer_keys?: string[];
		};
		/** @description Legacy scaffold; not wrapped in ResponseEnvelope. */
		PingResponse: {
			message?: string;
			core?: Record<string, never>[];
			cpu?: Record<string, never>[];
			memory?: Record<string, never>[];
		};
	};
	responses: {
		/** @description Missing or invalid bearer token */
		Unauthorized: {
			headers: {
				[name: string]: unknown;
			};
			content: {
				"application/json": components["schemas"]["ResponseEnvelope"];
			};
		};
		/** @description Resource not found */
		NotFound: {
			headers: {
				[name: string]: unknown;
			};
			content: {
				"application/json": components["schemas"]["ResponseEnvelope"];
			};
		};
		/** @description Validation or business rule failure */
		ValidationError: {
			headers: {
				[name: string]: unknown;
			};
			content: {
				"application/json": components["schemas"]["ResponseEnvelope"];
			};
		};
	};
	parameters: {
		page: number;
		limit: number;
		id_or_slug: string;
	};
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	listPublicCategories: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ResponseEnvelope"] & {
						data?: components["schemas"]["CategoryListData"];
					};
				};
			};
			404: components["responses"]["NotFound"];
		};
	};
	getPublicCategory: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id_or_slug: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ResponseEnvelope"] & {
						data?: components["schemas"]["Category"];
					};
				};
			};
			404: components["responses"]["NotFound"];
		};
	};
	listPublicProducts: {
		parameters: {
			query?: {
				page?: components["parameters"]["page"];
				limit?: components["parameters"]["limit"];
				search?: string;
				category_id?: string;
				category_slug?: string;
				sort?: "name_asc" | "name_desc" | "created_at_desc";
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ResponseEnvelope"] & {
						data?: components["schemas"]["ProductListData"];
					};
				};
			};
			400: components["responses"]["ValidationError"];
		};
	};
	getPublicProduct: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id_or_slug: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ResponseEnvelope"] & {
						data?: components["schemas"]["Product"];
					};
				};
			};
			404: components["responses"]["NotFound"];
		};
	};
	createCheckoutOrder: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["CheckoutRequest"];
			};
		};
		responses: {
			/** @description Order created */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ResponseEnvelope"] & {
						data?: components["schemas"]["CheckoutResponse"];
					};
				};
			};
			400: components["responses"]["ValidationError"];
			404: components["responses"]["NotFound"];
		};
	};
	getClientPing: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["PingResponse"];
				};
			};
			401: components["responses"]["Unauthorized"];
		};
	};
	upsertInternalClients: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["ClientInput"][];
			};
		};
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ResponseEnvelope"] & {
						data?: components["schemas"]["Client"][];
					};
				};
			};
			401: components["responses"]["Unauthorized"];
		};
	};
	findInternalClients: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["ClientFilter"];
			};
		};
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ResponseEnvelope"] & {
						data?: components["schemas"]["Client"][];
					};
				};
			};
			401: components["responses"]["Unauthorized"];
		};
	};
	deleteInternalClients: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["ClientFilter"];
			};
		};
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ResponseEnvelope"];
				};
			};
			401: components["responses"]["Unauthorized"];
		};
	};
	listAdminCategories: {
		parameters: {
			query?: {
				page?: components["parameters"]["page"];
				limit?: components["parameters"]["limit"];
				search?: string;
				is_active?: boolean;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ResponseEnvelope"] & {
						data?: components["schemas"]["CategoryListData"];
					};
				};
			};
			401: components["responses"]["Unauthorized"];
		};
	};
	createAdminCategory: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["CategoryCreateInput"];
			};
		};
		responses: {
			/** @description Created */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ResponseEnvelope"] & {
						data?: components["schemas"]["Category"];
					};
				};
			};
			401: components["responses"]["Unauthorized"];
			/** @description Conflict */
			409: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
		};
	};
	getAdminCategory: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id_or_slug: components["parameters"]["id_or_slug"];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ResponseEnvelope"] & {
						data?: components["schemas"]["Category"];
					};
				};
			};
			401: components["responses"]["Unauthorized"];
			404: components["responses"]["NotFound"];
		};
	};
	deleteAdminCategory: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id_or_slug: components["parameters"]["id_or_slug"];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ResponseEnvelope"];
				};
			};
			401: components["responses"]["Unauthorized"];
			404: components["responses"]["NotFound"];
		};
	};
	updateAdminCategory: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id_or_slug: components["parameters"]["id_or_slug"];
			};
			cookie?: never;
		};
		requestBody?: {
			content: {
				"application/json": components["schemas"]["CategoryUpdateInput"];
			};
		};
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ResponseEnvelope"] & {
						data?: components["schemas"]["Category"];
					};
				};
			};
			401: components["responses"]["Unauthorized"];
			404: components["responses"]["NotFound"];
		};
	};
	listAdminProducts: {
		parameters: {
			query?: {
				page?: components["parameters"]["page"];
				limit?: components["parameters"]["limit"];
				search?: string;
				category_id?: string;
				category_slug?: string;
				is_active?: boolean;
				sort?: "created_at_desc" | "name_asc" | "name_desc";
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ResponseEnvelope"] & {
						data?: components["schemas"]["ProductListData"];
					};
				};
			};
			401: components["responses"]["Unauthorized"];
		};
	};
	createAdminProduct: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"multipart/form-data": components["schemas"]["ProductCreateMultipartFields"];
			};
		};
		responses: {
			/** @description Created */
			201: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ResponseEnvelope"] & {
						data?: components["schemas"]["Product"];
					};
				};
			};
			400: components["responses"]["ValidationError"];
			401: components["responses"]["Unauthorized"];
		};
	};
	getAdminProduct: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id_or_slug: components["parameters"]["id_or_slug"];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ResponseEnvelope"] & {
						data?: components["schemas"]["Product"];
					};
				};
			};
			401: components["responses"]["Unauthorized"];
			404: components["responses"]["NotFound"];
		};
	};
	deleteAdminProduct: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id_or_slug: components["parameters"]["id_or_slug"];
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ResponseEnvelope"];
				};
			};
			401: components["responses"]["Unauthorized"];
			404: components["responses"]["NotFound"];
		};
	};
	updateAdminProduct: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id_or_slug: components["parameters"]["id_or_slug"];
			};
			cookie?: never;
		};
		requestBody?: {
			content: {
				"multipart/form-data": components["schemas"]["ProductUpdateMultipartFields"];
			};
		};
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ResponseEnvelope"] & {
						data?: components["schemas"]["Product"];
					};
				};
			};
			401: components["responses"]["Unauthorized"];
			404: components["responses"]["NotFound"];
		};
	};
	listAdminOrders: {
		parameters: {
			query?: {
				page?: components["parameters"]["page"];
				limit?: components["parameters"]["limit"];
				status?: string;
				customer_email?: string;
				order_number?: string;
				sort?: "created_at_desc" | "created_at_asc";
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ResponseEnvelope"] & {
						data?: components["schemas"]["OrderListData"];
					};
				};
			};
			401: components["responses"]["Unauthorized"];
		};
	};
	getAdminOrder: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				id_or_order_number: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description OK */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ResponseEnvelope"] & {
						data?: components["schemas"]["Order"];
					};
				};
			};
			401: components["responses"]["Unauthorized"];
			404: components["responses"]["NotFound"];
		};
	};
}
